export CUDA_VISIBLE_DEVICES="0,1"
num_gpus=2
data_name="nq_hotpotqa_train_autorefine_exp3"
export DATA_DIR="/mnt/shared-storage-user/safeag-share/syzhang/datasets/autorefine/data/${data_name}"

wandb_token="XXX"
WAND_PROJECT="exp-03"
export WANDB_MODE="offline"
export WANDB_API_KEY=$wandb_token
export WANDB_DIR="/mnt/shared-storage-user/safeag-share/syzhang/verl/exp-5/wandb"
export VLLM_ATTENTION_BACKEND=XFORMERS
export PATH=/usr/local/nvidia/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/nvidia/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda-12.8

export BASE_MODEL='/mnt/shared-storage-user/safeag-share/syzhang/models/Qwen2.5-3B-base'
export EXPERIMENT_NAME="fact-gdpo-qwen2.5-3b-exp5"

mkdir -p log/
PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    reward_model.reward_style="F1" \
    data.train_files=$DATA_DIR/train.parquet \
    data.val_files=$DATA_DIR/valid_500.parquet \
    data.train_data_num=null \
    data.val_data_num=null \
    data.train_batch_size=64 \
    data.val_batch_size=256 \
    data.max_prompt_length=6656 \
    data.max_response_length=512 \
    data.max_start_length=2048 \
    data.max_obs_length=512 \
    max_turns=5 \
    data.shuffle_train_dataloader=true \
    algorithm.adv_estimator=gdpo \
    algorithm.filter_groups.enable=false \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.refine_lambda=-1 \
    actor_rollout_ref.actor.refine_score=0.1 \
    actor_rollout_ref.actor.format_score=0.0 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.ppo_mini_batch_size=128 \
    actor_rollout_ref.actor.ppo_micro_batch_size=64 \
    actor_rollout_ref.actor.fsdp_config.param_offload=true \
    actor_rollout_ref.actor.fsdp_config.grad_offload=true \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=128 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=128 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    algorithm.no_think_rl=false \
    actor_rollout_ref.rollout.n_agent=20 \
    actor_rollout_ref.rollout.temperature=1 \
    actor_rollout_ref.actor.state_masking=true \
    trainer.logger=['wandb'] \
    +trainer.val_only=false \
    +trainer.val_before_train=true \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=$num_gpus \
    trainer.nnodes=1 \
    trainer.save_freq=300 \
    trainer.test_freq=100 \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=15 \
    trainer.total_training_steps=200 \
    trainer.default_hdfs_dir=null \
    trainer.default_local_dir="/mnt/shared-storage-user/safeag-share/syzhang/verl/exp-5/ckpts" \
    retriever.url="http://127.0.0.1:8081/retrieve" \
    retriever.topk=3 \
    2>&1 | tee log/$EXPERIMENT_NAME.log